In [1]:
import numpy as np

# A toy snippet from Shakespeare
docs = ['Anthony and Cleopatra Brutus Caesar romans worser',
        'Caesar Anthony Brutus Calpurnia romans',
        'The worser',
        'Brutus Caesar romans worser',
        'Caesar worser',
        'Anthony Caesar'
       ]

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True, stop_words='english')
B = cv.fit_transform(docs).toarray()
cv.get_feature_names_out()
B

array([[1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 1],
       [1, 0, 1, 0, 0, 0, 0]])

In [3]:
B[:,2] & B[:,5] & (~B[:,3])  # Boolean retrieval

array([1, 0, 0, 1, 0, 0])

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(stop_words='english')
F = tv.fit_transform(docs).toarray()
q = tv.transform(['romans Caesar']).toarray()
q

array([[0.        , 0.        , 0.59485466, 0.        , 0.        ,
        0.80383327, 0.        ]])

In [5]:
file = np.load('BathPages.npz') # Load from numpy compressed file
titles = file['titles']
docs = file['docs']

tv = TfidfVectorizer(stop_words='english')
F = tv.fit_transform(docs).toarray()
F.shape

q = tv.transform(['Car park']).toarray()  # Transform a new query to the same TF-IDF model
q

array([[0., 0., 0., ..., 0., 0., 0.]])

In [6]:
# Cosine similarity scoring - exploiting ||q|| = ||f_i|| = 1
imax = np.argmax(F @ q.T)
print(titles[imax])
print(docs[imax])

East Car Park Overflow
Skip to main content

  * Courses
  * Research
  * Enterprise
  * Sport
  * Departments
  * About

  * _From_ Security 

# East Car Park Overflow

The East Car Park Overflow has 231 car parking spaces for permit holders on
the Claverton Down campus. You can access it from the rear of the East Car
Park.

  * Car park
  * View more locations in Security 

# Address

East Car Park Overflow University of Bath Claverton Down Bath BA2 7AY United
Kingdom

Find your way here using Google Maps

# GPS coordinates

Latitude 51.37699  
Longitude -2.32069

# Map for this location

  
View Larger Map

# Additional information

This car park is for permit holders only. Occasional user permit holders can
validate their permit using JustPark. There is public Pay and Parl parking
nearby in the East Car Park.

## Capacity

There are 231 car spaces for permit holders only.

# Accessibility

There are no accessible car parking spaces available in the East Car Park
Overflow, but there